config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'gossip#index'

  get '/welcome', to: 'bienvenue#welcome'
  get '/team', to: 'static#team'
  get '/contact', to: 'static#contact'
  
  get '/:id', to: 'bienvenue#one_gossip'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :author, class_name: "User"

def self.search(search)
  where("name LIKE ?", "%#{search}%")
  where("content LIKE ?", "%#{search}%")
end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips, foreign_key: :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bienvenue_controller.rb
class BienvenueController < ApplicationController
  def welcome
    puts params
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def index
    @gossips_all = Gossip.all

    if params[:search]
      @gossips_all = Gossip.search(params[:search]).order("created_at DESC")
    else
      @gossips_all = Gossip.all.order('created_at DESC')
    end
    # puts "_______________________________________________________________________"
    # # puts params[:search]
    # u = User.where(name: params[:search])
    # puts u.gossips
    # puts "_______________________________________________________________________"
    # puts u.author_id
    # puts Gossip.where(author_id.user: params[:search])

  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def team
    @user_all = User.all
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenue_helper.rb
module BienvenueHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/bienvenue/one_gossip.erb
<br>
<h1>Gossip n° <%= params["id"] %> </h1><br>

<h3><%= Gossip.find(params["id"]).author.name %></h3>
    <p>"<%= Gossip.find(params["id"]).content %>"</p>

app/views/bienvenue/welcome.html.erb
<br><h1>Welcome, man !</h1>
<br><h4>Wanna join the club ? Leave your gossip online ! </h4>

<div class="row">


<div class="form-group col-5">
  <label class="col-form-label" for="inputDefault">Name</label>
  <input type="text" class="form-control" placeholder="Your name here..." id="inputDefault">
</div>

<div class="form-group col-5">
  <label class="col-form-label" for="inputDefault">Content</label>
  <input type="text" class="form-control" placeholder="Tell us everything..." id="inputDefault">
</div>

<div class="col-2">
  <button type="s" class="btn btn-danger disabled center">Submit !</button>
</div>

</div>

app/views/gossip/index.html.erb
<br>
<h1>Welcome to the best Gossip website man !</h1><br>

<h3>Take a look at this, I mean... WaaaoOOowww </h3><br>

<div class="row">

  <% @gossips_all.each do |gossip| %>
<div class="card border-secondary mb-3 col-3" style="max-width: 20rem;">

  <div class="card-header"><button type="button" class="btn btn-danger disabled"><%= link_to "Gossip n°#{gossip.id}", "#{gossip.id}" %></button>   << click here to see !</div>
  <div class="card-body">
    <h4 class="card-title"><%= gossip.author.name %></h4>
    <p class="card-text">"<%= gossip.content %>"</p>
  </div>
</div>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>

    <title>Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">Gossip Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link"<%= link_to "Welcome", welcome_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Team", team_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Contact", contact_path %></a>
          </li>
        </ul>
        <%= form_tag("https://www.google.fr", :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Gossip" %>
        <%= submit_tag "Search" %>
        <% end %>

      </div>
    </nav>

    <%= yield %>
  </body>
</html>